# Generated by Django 4.2.6 on 2023-10-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100, null=True)),
                ('item_image', models.ImageField(upload_to='item_images/')),
            ],
        ),
    ]
