# Generated by Django 4.2.6 on 2023-10-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallmarkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='book_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='content_1',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='content_2',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='content_3',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(null=True, upload_to='item_images/'),
        ),
    ]
