# Generated by Django 4.2.6 on 2023-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallmarkapp', '0003_item_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
